### ISSUE TITLE
Module description

### ISSUE THREAD

**Issue by kgryte** [compute-io/matrix-number-function#2]
The current description is

> Applies a function to each matrix element by broadcasting numeric arguments.

I am not sold that this is best way of describing these types of modules. 

> Applies a function to each matrix element while broadcasting numeric arguments.

Anything thoughts on phrasing or maybe something different altogether?

**Comment by Planeshifter** [comment]
Of the two given sentences, I prefer the second one as its emphasis is on the function application for each matrix element, with the broadcasting being a detail; the term _broadcasting_ itself seems to be quite common for describing the process of expanding arrays / numbers to a common size. It appears both in the documentation of Python's numpy library and Julia, although I don't find it too intuitive personally. I would have thought more of something along the lines of

> Applies a function to each matrix element while recycling / repeating numeric arguments.

But since _broadcasting_ seems to be used almost universally, :+1: for going with your second description.

**Comment by kgryte** [comment]
Cool. Thanks! Yeah, agreed on the use of _broadcasting_. I am not sure how its use in this context originated. Once known, however, provides a reasonably concise desc. Will make the change from `by` to `while`.
